
services:
  app:
    build:
      context: . # Build from the Dockerfile in the current directory
    container_name: express_app
    ports:
      - "5000:5000"  # Map port 5000 on the host to 5000 in the container
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=hidran123
      - DB_NAME=tododb
      - DB_PORT=3306
      - PORT=5000
    depends_on:
      - mysql  # Wait for MySQL to be ready before starting the app
    volumes:
      - .:/usr/src/app  # Mount the current directory for live reload (optional, use with nodemon for development)

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3309:3306"  # Map port 3306 on the host to 3306 in the container
    environment:
      restart: always
      MYSQL_ROOT_PASSWORD: hidran123
      MYSQL_DATABASE: tododb
    volumes:
      - mysql_data2:/var/lib/mysql  # Persist MySQL data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql_data2:
